# Generated by Django 4.2.30 on 2026-06-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("reviewer", "Reviewer"),
                    ("author", "Author"),
                ],
                default="author",
                max_length=20,
            ),
        ),
    ]
