# Generated by Django 4.2.30 on 2026-06-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewcomment",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
